language: node_js

node_js:
- '--lts'

os:
- linux
- osx

before_install:
- if [ $TRAVIS_OS_NAME == "linux" ]; then
    export DISPLAY=':99.0'
    /usr/bin/Xvfb :99 -screen 0 1024x768x24 > /dev/null 2>&1 &
  fi

install:
- npm install -g vsce
- npm install -g typescript
- npm install -g gulp
- npm install

script:
- gulp tslint
- vsce package
- npm test
